server:
  #服务器端口
  port: 26666
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://数据库地址:3306/数据库名称?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: 数据库用户名
    password: 数据库密码
  main:
    allow-bean-definition-overriding: true
  mvc: #静态文件
    static-path-pattern: /static/**
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  type-aliases-package: com.oldwu.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl